"""add correction retry lineage

Revision ID: 0c23b3ef3df1
Revises: 6a193ffbcd98
Create Date: 2026-08-25 20:33:05.441085

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0c23b3ef3df1'
down_revision: str | Sequence[str] | None = '6a193ffbcd98'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('self_correction_sessions', sa.Column('parent_session_id', sa.UUID(), nullable=True))
    op.add_column('self_correction_sessions', sa.Column('last_verification_run_id', sa.UUID(), nullable=True))
    op.create_index('ix_self_correction_sessions_last_verification_run_id', 'self_correction_sessions', ['last_verification_run_id'], unique=False)
    op.create_index('ix_self_correction_sessions_parent_session_id', 'self_correction_sessions', ['parent_session_id'], unique=False)
    op.create_foreign_key(None, 'self_correction_sessions', 'verification_runs', ['last_verification_run_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'self_correction_sessions', 'self_correction_sessions', ['parent_session_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'self_correction_sessions', type_='foreignkey')
    op.drop_constraint(None, 'self_correction_sessions', type_='foreignkey')
    op.drop_index('ix_self_correction_sessions_parent_session_id', table_name='self_correction_sessions')
    op.drop_index('ix_self_correction_sessions_last_verification_run_id', table_name='self_correction_sessions')
    op.drop_column('self_correction_sessions', 'last_verification_run_id')
    op.drop_column('self_correction_sessions', 'parent_session_id')
    # ### end Alembic commands ###
