"""add correction proposal fields

Revision ID: 1085931e1328
Revises: f921937d79a9
Create Date: 2026-08-25 17:57:52.209889

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1085931e1328'
down_revision: str | Sequence[str] | None = 'f921937d79a9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('self_correction_sessions', sa.Column('proposal_json', sa.JSON(), nullable=True))
    op.add_column('self_correction_sessions', sa.Column('proposal_generated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('self_correction_sessions', 'proposal_generated_at')
    op.drop_column('self_correction_sessions', 'proposal_json')
    # ### end Alembic commands ###
