"""link correction sessions to pending patches

Revision ID: 6a193ffbcd98
Revises: 1085931e1328
Create Date: 2026-08-25 20:03:57.581094

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6a193ffbcd98'
down_revision: str | Sequence[str] | None = '1085931e1328'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('self_correction_patches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('pending_patch_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('position >= 1', name='ck_self_correction_patches_position_positive'),
    sa.ForeignKeyConstraint(['pending_patch_id'], ['pending_patches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['self_correction_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pending_patch_id', name='uq_self_correction_patches_pending_patch_id'),
    sa.UniqueConstraint('session_id', 'position', name='uq_self_correction_patches_session_position')
    )
    op.create_index('ix_self_correction_patches_session_id', 'self_correction_patches', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_self_correction_patches_session_id', table_name='self_correction_patches')
    op.drop_table('self_correction_patches')
    # ### end Alembic commands ###
