"""add self correction sessions

Revision ID: f921937d79a9
Revises: 168813304978
Create Date: 2026-08-25 17:42:21.961564

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f921937d79a9'
down_revision: str | Sequence[str] | None = '168813304978'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('self_correction_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('source_verification_run_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_attempt', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('failure_type', sa.String(length=50), nullable=False),
    sa.Column('failure_summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_verification_run_id'], ['verification_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_self_correction_sessions_source_verification_run_id'), 'self_correction_sessions', ['source_verification_run_id'], unique=False)
    op.create_index(op.f('ix_self_correction_sessions_task_id'), 'self_correction_sessions', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_self_correction_sessions_task_id'), table_name='self_correction_sessions')
    op.drop_index(op.f('ix_self_correction_sessions_source_verification_run_id'), table_name='self_correction_sessions')
    op.drop_table('self_correction_sessions')
    # ### end Alembic commands ###
